INSERT INTO candidates (id, name, experience_years, skills, previous_role)
VALUES
(1, 'Walter Bechtelar', 6, 'Lean Manufacturing, Crisis Management, Team Leadership', 'International Accounts Specialist'),
(2, 'Phillip Roob', 2, 'Lean Manufacturing, Process Optimization, Crisis Management', 'Direct Program Executive'),
(3, 'Alberta Veum PhD', 4, 'Lean Manufacturing, Team Leadership, Safety Compliance', 'Customer Mobility Associate'),
(4, 'Joan Marks', 15, 'Safety Compliance, Lean Manufacturing, Process Optimization', 'Product Optimization Consultant'),
(5, 'Salvador Adams', 8, 'Team Leadership, Crisis Management, Process Optimization', 'District Factors Manager'),
(6, 'Geraldine Cummings', 13, 'Sustainability, Crisis Management, Safety Compliance', 'Internal Quality Associate'),
(7, 'Jean Quitzon', 9, 'Safety Compliance, Process Optimization, Lean Manufacturing', 'Direct Intranet Manager'),
(8, 'Mr. Hugo Aufderhar', 6, 'Lean Manufacturing, Crisis Management, Safety Compliance', 'Customer Program Planner'),
(9, 'Bradford Kihn', 12, 'Crisis Management, Sustainability, Process Optimization', 'District Implementation Strategist'),
(10, 'Josephine Thiel', 15, 'Team Leadership, Lean Manufacturing, Crisis Management', 'National Branding Associate'),
(11, 'Carl Senger', 13, 'Lean Manufacturing, Process Optimization, Crisis Management', 'Direct Infrastructure Technician'),
(12, 'Claude Muller', 10, 'Process Optimization, Lean Manufacturing, Safety Compliance', 'Investor Security Executive'),
(13, 'Rose Kuhn', 4, 'Process Optimization, Lean Manufacturing, Sustainability', 'Central Infrastructure Executive'),
(14, 'Merle Sporer', 4, 'Process Optimization, Crisis Management, Safety Compliance', 'Chief Optimization Coordinator'),
(15, 'Stacy Daugherty IV', 5, 'Team Leadership, Safety Compliance, Crisis Management', 'Direct Web Coordinator'),
(16, 'James Howell', 4, 'Lean Manufacturing, Safety Compliance, Process Optimization', 'Senior Identity Consultant'),
(17, 'Ted Will Sr.', 2, 'Team Leadership, Sustainability, Lean Manufacturing', 'Product Usability Planner'),
(18, 'Dr. Hugh Kub', 2, 'Safety Compliance, Crisis Management, Sustainability', 'Senior Markets Producer'),
(19, 'Lora Quigley', 10, 'Sustainability, Process Optimization, Crisis Management', 'Principal Marketing Technician'),
(20, 'Dr. Denise Zulauf', 13, 'Sustainability, Crisis Management, Process Optimization', 'Chief Usability Supervisor'),
(21, 'Shaun Marvin', 11, 'Process Optimization, Sustainability, Crisis Management', 'Legacy Marketing Technician'),
(22, 'Rachael Sanford', 13, 'Crisis Management, Team Leadership, Process Optimization', 'Direct Solutions Representative'),
(23, 'Jeanette Lang', 10, 'Process Optimization, Sustainability, Safety Compliance', 'Global Infrastructure Executive'),
(24, 'Charles Altenwerth Sr.', 5, 'Sustainability, Process Optimization, Safety Compliance', 'Legacy Identity Architect'),
(25, 'Mrs. Alexandra Oberbrunner', 14, 'Process Optimization, Team Leadership, Sustainability', 'District Integration Orchestrator'),
(26, 'Ms. Carolyn Thompson', 8, 'Crisis Management, Lean Manufacturing, Process Optimization', 'Product Brand Producer'),
(27, 'Angelica Sipes', 11, 'Team Leadership, Sustainability, Safety Compliance', 'Chief Quality Engineer'),
(28, 'Troy Johnson', 14, 'Safety Compliance, Crisis Management, Process Optimization', 'Senior Security Director'),
(29, 'Mr. James Weissnat', 4, 'Process Optimization, Lean Manufacturing, Team Leadership', 'Global Usability Strategist'),
(30, 'Alex Gibson IV', 12, 'Team Leadership, Safety Compliance, Sustainability', 'Global Communications Analyst'),
(31, 'Nick Huel', 13, 'Crisis Management, Safety Compliance, Lean Manufacturing', 'National Mobility Facilitator'),
(32, 'Alexis Yost-Tromp', 3, 'Crisis Management, Process Optimization, Safety Compliance', 'Central Brand Administrator'),
(33, 'Mr. Bradford Hauck', 3, 'Process Optimization, Team Leadership, Sustainability', 'Regional Security Technician'),
(34, 'Harold Bartell', 12, 'Safety Compliance, Crisis Management, Process Optimization', 'Investor Program Producer'),
(35, 'Beverly Waelchi III', 14, 'Safety Compliance, Process Optimization, Crisis Management', 'Regional Configuration Agent'),
(36, 'Veronica Parisian', 10, 'Safety Compliance, Sustainability, Crisis Management', 'District Group Engineer'),
(37, 'Miss Lucy Robel Jr.', 12, 'Sustainability, Process Optimization, Crisis Management', 'Internal Solutions Officer'),
(38, 'Marcos Lang-Sporer DDS', 5, 'Lean Manufacturing, Safety Compliance, Sustainability', 'Internal Functionality Representative'),
(39, 'Shane Stamm', 13, 'Crisis Management, Safety Compliance, Team Leadership', 'Principal Research Administrator'),
(40, 'Julie Ortiz', 11, 'Process Optimization, Sustainability, Lean Manufacturing', 'Senior Solutions Associate');